bugfix optiongroupserializer missing
django-oscar/django-oscar-api pull request #344
Opened 2024-04-11 08:05 UTC by svandeneertwegh

Added:
`option_group = AttributeOptionGroupSerializer()`

to:

```class OptionSerializer(OscarHyperlinkedModelSerializer):```

in file: oscarapi/serializers/product.py

2024-04-11 08:08 UTC, svandeneertwegh commented
This fixes the problem mentioned at #324 !

2024-04-12 06:29 UTC, specialunderwear requested changes

2024-04-12 06:29 UTC, specialunderwear commented on oscarapi/serializers/product.py
> +    option_group = AttributeOptionGroupSerializer()
Hi, I think this should be optional, the tests are failing atm!

2024-04-12 06:29 UTC, specialunderwear commented on oscarapi/serializers/product.py
> +    option_group = AttributeOptionGroupSerializer()
Also I think it is important to demonstrate the problem in a test, to make sure there are no regressions in the future

2024-04-12 07:53 UTC, svandeneertwegh commented
@specialunderwear when this is not applied i get errors on admin endpoints when i set:
`OSCARAPI_BLOCK_ADMIN_API_ACCESS = False`

2024-04-15 06:58 UTC, specialunderwear requested changes

2024-04-15 06:58 UTC, specialunderwear commented on Makefile
> +        coverage xml -i
This has to be a tab, you broke the tests by making them spaces

2024-09-19 07:19 UTC, specialunderwear approved these changes

2024-11-25 19:25 UTC, merged